name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          [
            api-gateway,
            customer-services,
            inventory-services,
            menu-services,
            order-services,
            payment-services,
          ]

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image for ${{ matrix.service }}
        run: docker build . --file ${{ matrix.service }}/Dockerfile --tag ${{ matrix.service }}:${{ github.sha }}
        working-directory: ./${{ matrix.service }}
