
name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        service:
          [
            api-gateway,
            customer-services,
            inventory-services,
            menu-services,
            order-services,
            payment-services,
          ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ${{ matrix.service }}/package-lock.json 
      - name: Install dependencies for ${{ matrix.service }}
        run: npm ci
        working-directory: ./${{ matrix.service }}
      - name: Build ${{ matrix.service }} (if applicable)
        run: npm run build --if-present
        working-directory: ./${{ matrix.service }}
      - name: Test ${{ matrix.service }}
        run: npm test
        working-directory: ./${{ matrix.service }}
